name: CI
on: 
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - '**.md'
      - '**.txt'
      - '!CMakeLists.txt'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - "docs/**"
      - '**.md'
      - '**.txt'
      - '!CMakeLists.txt'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        unrar_target: [unrar-win64, unrar-win32, unrar-arm64]
        include:
          - unrar_target: unrar-win64
            short_target: win64
          - unrar_target: unrar-win32
            short_target: win32
          - unrar_target: unrar-arm64
            short_target: arm64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: compile-unrar
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
          workdir: ${{ matrix.build_dir }}
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./build.ps1" -Target "${{ matrix.short_target }}"

      - name: Package release
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        # create package and show sha256 hash
        run: |
          Set-Location build
          # cleanup zip files
          Remove-Item -Force *.zip
          cpack -G ZIP
          $item=Get-Item unrar*.zip
          $obj=Get-FileHash -Algorithm SHA256 $item.FullName
          $baseName=Split-Path -Leaf $item.FullName
          $env:UNRAR_ASSET_NAME="$baseName"
          $hashtext=$obj.Algorithm+":"+$obj.Hash.ToLower()
          $hashtext|Out-File -Encoding utf8 -FilePath "$baseName.sum"
          Write-Host "$env:UNRAR_ASSET_NAME`n$hashtext"
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/unrar-*.zip
          tag: ${{ github.ref }}
          overwrite: true
